//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapBul.Web.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JavaScriptResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JavaScriptResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapBul.Web.Resource.JavaScriptResource", typeof(JavaScriptResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/Admins.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/ArticleCategories.
        /// </summary>
        public static string ArticleCategories {
            get {
                return ResourceManager.GetString("ArticleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/Dictionaries.
        /// </summary>
        public static string Dictionaries {
            get {
                return ResourceManager.GetString("Dictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/Editors.
        /// </summary>
        public static string Editors {
            get {
                return ResourceManager.GetString("Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/Guides.
        /// </summary>
        public static string Guides {
            get {
                return ResourceManager.GetString("Guides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/Journalists.
        /// </summary>
        public static string Journalists {
            get {
                return ResourceManager.GetString("Journalists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/MarkerCategories.
        /// </summary>
        public static string MarkerCategories {
            get {
                return ResourceManager.GetString("MarkerCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/Markers.
        /// </summary>
        public static string Markers {
            get {
                return ResourceManager.GetString("Markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/Tenants.
        /// </summary>
        public static string Tenants {
            get {
                return ResourceManager.GetString("Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/CustomScripts/Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
