//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapBul.Web.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("MapBul.Web.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link to city.
        /// </summary>
        public static string ArtAddLinkToCity {
            get {
                return ResourceManager.GetString("ArtAddLinkToCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link to pin.
        /// </summary>
        public static string ArtAddLinkToPin {
            get {
                return ResourceManager.GetString("ArtAddLinkToPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article affiliated members.
        /// </summary>
        public static string ArtArticleAffiliatedMembers {
            get {
                return ResourceManager.GetString("ArtArticleAffiliatedMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article photo.
        /// </summary>
        public static string ArtArticlePhoto {
            get {
                return ResourceManager.GetString("ArtArticlePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event end date.
        /// </summary>
        public static string ArtEventEndDate {
            get {
                return ResourceManager.GetString("ArtEventEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event start date.
        /// </summary>
        public static string ArtEventStartDate {
            get {
                return ResourceManager.GetString("ArtEventStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event start time.
        /// </summary>
        public static string ArtEventStartTime {
            get {
                return ResourceManager.GetString("ArtEventStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header photo.
        /// </summary>
        public static string ArtHeaderPhoto {
            get {
                return ResourceManager.GetString("ArtHeaderPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My articles.
        /// </summary>
        public static string ArtMyArticles {
            get {
                return ResourceManager.GetString("ArtMyArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New article.
        /// </summary>
        public static string ArtNewArticle {
            get {
                return ResourceManager.GetString("ArtNewArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New article photo.
        /// </summary>
        public static string ArtNewArticlePhoto {
            get {
                return ResourceManager.GetString("ArtNewArticlePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New header photo.
        /// </summary>
        public static string ArtNewHeaderPhoto {
            get {
                return ResourceManager.GetString("ArtNewHeaderPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source link.
        /// </summary>
        public static string ArtSourceLink {
            get {
                return ResourceManager.GetString("ArtSourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base category.
        /// </summary>
        public static string BaseCategory {
            get {
                return ResourceManager.GetString("BaseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string DicAdd {
            get {
                return ResourceManager.GetString("DicAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article categoryes.
        /// </summary>
        public static string DicArticleCategoryes {
            get {
                return ResourceManager.GetString("DicArticleCategoryes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag category to change order.
        /// </summary>
        public static string DicCategoryDrag {
            get {
                return ResourceManager.GetString("DicCategoryDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category icon.
        /// </summary>
        public static string DicCategoryIcon {
            get {
                return ResourceManager.GetString("DicCategoryIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optimal size of 120x120 icons, icons of other sizes are scaled to the specified).
        /// </summary>
        public static string DicCategoryIconText {
            get {
                return ResourceManager.GetString("DicCategoryIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string DicCategoryName {
            get {
                return ResourceManager.GetString("DicCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category order.
        /// </summary>
        public static string DicCategoryOrder {
            get {
                return ResourceManager.GetString("DicCategoryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category pin icon.
        /// </summary>
        public static string DicCategoryPinIcon {
            get {
                return ResourceManager.GetString("DicCategoryPinIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string DicCities {
            get {
                return ResourceManager.GetString("DicCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string DicColor {
            get {
                return ResourceManager.GetString("DicColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string DicCountries {
            get {
                return ResourceManager.GetString("DicCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag category to change order.
        /// </summary>
        public static string DicDragCategoryText {
            get {
                return ResourceManager.GetString("DicDragCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DicEdit {
            get {
                return ResourceManager.GetString("DicEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        public static string DicEditCategory {
            get {
                return ResourceManager.GetString("DicEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category.
        /// </summary>
        public static string DicNewCategory {
            get {
                return ResourceManager.GetString("DicNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New city.
        /// </summary>
        public static string DicNewCity {
            get {
                return ResourceManager.GetString("DicNewCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New country.
        /// </summary>
        public static string DicNewCountry {
            get {
                return ResourceManager.GetString("DicNewCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent category.
        /// </summary>
        public static string DicParentCategory {
            get {
                return ResourceManager.GetString("DicParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins category.
        /// </summary>
        public static string DicPinsCategory {
            get {
                return ResourceManager.GetString("DicPinsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions and cities.
        /// </summary>
        public static string DicRegionsAndCities {
            get {
                return ResourceManager.GetString("DicRegionsAndCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        public static string DicSelectACategory {
            get {
                return ResourceManager.GetString("DicSelectACategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not choosen.
        /// </summary>
        public static string FileNotChoosen {
            get {
                return ResourceManager.GetString("FileNotChoosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string NavArticles {
            get {
                return ResourceManager.GetString("NavArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionaries.
        /// </summary>
        public static string NavDictionaries {
            get {
                return ResourceManager.GetString("NavDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins.
        /// </summary>
        public static string NavPins {
            get {
                return ResourceManager.GetString("NavPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string NavUsers {
            get {
                return ResourceManager.GetString("NavUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records.
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin affiliated members.
        /// </summary>
        public static string PinAffiliatedMembers {
            get {
                return ResourceManager.GetString("PinAffiliatedMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string PinBuilding {
            get {
                return ResourceManager.GetString("PinBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string PinClose {
            get {
                return ResourceManager.GetString("PinClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string PinDiscount {
            get {
                return ResourceManager.GetString("PinDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or, enter the coordinates.
        /// </summary>
        public static string PinEnterTheCoordinates {
            get {
                return ResourceManager.GetString("PinEnterTheCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance fee.
        /// </summary>
        public static string PinEntranceFee {
            get {
                return ResourceManager.GetString("PinEntranceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string PinFloor {
            get {
                return ResourceManager.GetString("PinFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string PinHouse {
            get {
                return ResourceManager.GetString("PinHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude .
        /// </summary>
        public static string PinLatitude {
            get {
                return ResourceManager.GetString("PinLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string PinLogo {
            get {
                return ResourceManager.GetString("PinLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Image in the popup window, the optimal size of 300x300).
        /// </summary>
        public static string PinLogoText {
            get {
                return ResourceManager.GetString("PinLogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string PinLongitude {
            get {
                return ResourceManager.GetString("PinLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New pin.
        /// </summary>
        public static string PinNewPin {
            get {
                return ResourceManager.GetString("PinNewPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string PinOpen {
            get {
                return ResourceManager.GetString("PinOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open hours.
        /// </summary>
        public static string PinOpenHours {
            get {
                return ResourceManager.GetString("PinOpenHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string PinPhoto {
            get {
                return ResourceManager.GetString("PinPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Pictures are displayed in the description pin).
        /// </summary>
        public static string PinPhotoText {
            get {
                return ResourceManager.GetString("PinPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preamble.
        /// </summary>
        public static string PinPreamble {
            get {
                return ResourceManager.GetString("PinPreamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins.
        /// </summary>
        public static string Pins {
            get {
                return ResourceManager.GetString("Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a tag.
        /// </summary>
        public static string PinSelectAtag {
            get {
                return ResourceManager.GetString("PinSelectAtag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city from list.
        /// </summary>
        public static string PinSelectCityFromList {
            get {
                return ResourceManager.GetString("PinSelectCityFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string PinStreet {
            get {
                return ResourceManager.GetString("PinStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System pins.
        /// </summary>
        public static string PinSystemPins {
            get {
                return ResourceManager.GetString("PinSystemPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi.
        /// </summary>
        public static string PinWiFi {
            get {
                return ResourceManager.GetString("PinWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required fields *.
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        public static string SelectAFile {
            get {
                return ResourceManager.GetString("SelectAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select сountry.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWW.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
    }
}
